name = "NEO"
uuid = "081d0416-0f87-42c0-8034-5895805e76d8"
authors = ["adrianaghiozzi <67669644+adrianaghiozzi@users.noreply.github.com>"]
version = "2.0.1"

[deps]
GACODE = "bb074124-7a58-47ce-bd41-6b7098184f23"
IMAS = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[compat]
IMAS = "2, 3, 4, 5"
SpecialFunctions = "2"
